// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// linreg_group_lasso_lambda_max_cpp
double linreg_group_lasso_lambda_max_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::IntegerVector group);
RcppExport SEXP _kfl1ou_linreg_group_lasso_lambda_max_cpp(SEXP xSEXP, SEXP ySEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(linreg_group_lasso_lambda_max_cpp(x, y, group));
    return rcpp_result_gen;
END_RCPP
}
// linreg_group_lasso_path_cpp
Rcpp::List linreg_group_lasso_path_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::IntegerVector group, Rcpp::NumericVector lambda, double tol, int max_iter, int inner_loops, double beta_ls, double sigma_ls, bool line_search);
RcppExport SEXP _kfl1ou_linreg_group_lasso_path_cpp(SEXP xSEXP, SEXP ySEXP, SEXP groupSEXP, SEXP lambdaSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP inner_loopsSEXP, SEXP beta_lsSEXP, SEXP sigma_lsSEXP, SEXP line_searchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type inner_loops(inner_loopsSEXP);
    Rcpp::traits::input_parameter< double >::type beta_ls(beta_lsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_ls(sigma_lsSEXP);
    Rcpp::traits::input_parameter< bool >::type line_search(line_searchSEXP);
    rcpp_result_gen = Rcpp::wrap(linreg_group_lasso_path_cpp(x, y, group, lambda, tol, max_iter, inner_loops, beta_ls, sigma_ls, line_search));
    return rcpp_result_gen;
END_RCPP
}
// add_configuration_score_to_db
void add_configuration_score_to_db(std::string str_key, double value, std::string mInfo);
RcppExport SEXP _kfl1ou_add_configuration_score_to_db(SEXP str_keySEXP, SEXP valueSEXP, SEXP mInfoSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type str_key(str_keySEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type mInfo(mInfoSEXP);
    add_configuration_score_to_db(str_key, value, mInfo);
    return R_NilValue;
END_RCPP
}
// get_stored_config_score
Rcpp::List get_stored_config_score();
RcppExport SEXP _kfl1ou_get_stored_config_score() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_stored_config_score());
    return rcpp_result_gen;
END_RCPP
}
// erase_configuration_score_db
void erase_configuration_score_db();
RcppExport SEXP _kfl1ou_erase_configuration_score_db() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    erase_configuration_score_db();
    return R_NilValue;
END_RCPP
}
// get_score_of_configuration
Rcpp::List get_score_of_configuration(std::string str_key);
RcppExport SEXP _kfl1ou_get_score_of_configuration(SEXP str_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type str_key(str_keySEXP);
    rcpp_result_gen = Rcpp::wrap(get_score_of_configuration(str_key));
    return rcpp_result_gen;
END_RCPP
}
// get_runtime_thread_settings
Rcpp::List get_runtime_thread_settings();
RcppExport SEXP _kfl1ou_get_runtime_thread_settings() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_runtime_thread_settings());
    return rcpp_result_gen;
END_RCPP
}
// set_runtime_thread_settings
Rcpp::List set_runtime_thread_settings(int blas_threads, int openmp_threads);
RcppExport SEXP _kfl1ou_set_runtime_thread_settings(SEXP blas_threadsSEXP, SEXP openmp_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type blas_threads(blas_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type openmp_threads(openmp_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(set_runtime_thread_settings(blas_threads, openmp_threads));
    return rcpp_result_gen;
END_RCPP
}
// cmp_sqrt_OU_covariance
Rcpp::List cmp_sqrt_OU_covariance(Rcpp::NumericMatrix edgeList, int nTips, double rootEdge);
RcppExport SEXP _kfl1ou_cmp_sqrt_OU_covariance(SEXP edgeListSEXP, SEXP nTipsSEXP, SEXP rootEdgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edgeList(edgeListSEXP);
    Rcpp::traits::input_parameter< int >::type nTips(nTipsSEXP);
    Rcpp::traits::input_parameter< double >::type rootEdge(rootEdgeSEXP);
    rcpp_result_gen = Rcpp::wrap(cmp_sqrt_OU_covariance(edgeList, nTips, rootEdge));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void effectiveSampleSize(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void threepoint_l1ou(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CMethodDef CEntries[] = {
    {"effectiveSampleSize", (DL_FUNC) &effectiveSampleSize, 10},
    {"threepoint_l1ou",     (DL_FUNC) &threepoint_l1ou,     13},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"_kfl1ou_linreg_group_lasso_lambda_max_cpp", (DL_FUNC) &_kfl1ou_linreg_group_lasso_lambda_max_cpp, 3},
    {"_kfl1ou_linreg_group_lasso_path_cpp", (DL_FUNC) &_kfl1ou_linreg_group_lasso_path_cpp, 10},
    {"_kfl1ou_add_configuration_score_to_db", (DL_FUNC) &_kfl1ou_add_configuration_score_to_db, 3},
    {"_kfl1ou_get_stored_config_score", (DL_FUNC) &_kfl1ou_get_stored_config_score, 0},
    {"_kfl1ou_erase_configuration_score_db", (DL_FUNC) &_kfl1ou_erase_configuration_score_db, 0},
    {"_kfl1ou_get_score_of_configuration", (DL_FUNC) &_kfl1ou_get_score_of_configuration, 1},
    {"_kfl1ou_get_runtime_thread_settings", (DL_FUNC) &_kfl1ou_get_runtime_thread_settings, 0},
    {"_kfl1ou_set_runtime_thread_settings", (DL_FUNC) &_kfl1ou_set_runtime_thread_settings, 2},
    {"_kfl1ou_cmp_sqrt_OU_covariance", (DL_FUNC) &_kfl1ou_cmp_sqrt_OU_covariance, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_kfl1ou(DllInfo *dll) {
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
